name: 'WissKI base (dev branch)'
description: 'WissKI base environment (development branch) with mandatory modules.'
type: 'Site'

install:
  - inline_entity_form
  - wisski
  
config:
  import:
    inline_entity_form: "*"
    wisski: "*"
